from fpdf import FPDF

def generate_customs_pdf(d):
    """Generuje plik PDF z danymi deklaracji celnej."""
    pdf = FPDF()
    pdf.add_page()
    
    # --- NAGŁÓWEK ---
    pdf.set_fill_color(224, 242, 254)  # Jasnoniebieski tło
    pdf.rect(0, 0, 210, 40, 'F')
    
    pdf.set_font("helvetica", "B", 18)
    pdf.set_text_color(2, 132, 199) # Ciemnoniebieski
    pdf.cell(0, 15, "CUSTOMS DECLARATION", ln=True, align='C')
    
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(100, 116, 139) # Szary
    pdf.cell(0, 5, "CBP Form 6059B (Traveler Cheat Sheet)", ln=True, align='C')
    pdf.ln(10)
    
    # --- DANE OSOBOWE ---
    pdf.set_text_color(0, 0, 0)
    
    def add_field(label, value, num):
        pdf.set_font("helvetica", "B", 10)
        pdf.set_text_color(2, 132, 199)
        pdf.write(7, f"{num}. {label}: ")
        pdf.set_font("helvetica", "B", 11)
        pdf.set_text_color(198, 40, 40) # Czerwony dla odpowiedzi
        pdf.write(7, f"{value}\n")
        pdf.ln(3)

    add_field("Family Name, First Name", f"{d['c_last']} {d['c_first']}", "1")
    add_field("Birth date (MM/DD/YY)", d['c_dob'], "2")
    add_field("Number of family members traveling", str(d['c_mem']), "3")
    add_field("U.S. Street Address / Hotel", f"{d['c_street']}, {d['c_city']}, {d['c_state']}", "4")
    add_field("Passport issued by / Number", f"{d['c_pass_country']} / {d['c_pass_no']}", "5-6")
    add_field("Country of Residence", d['c_residence'], "7")
    add_field("Countries visited prior to U.S.", d['c_visited'], "8")
    add_field("Airline / Flight No.", d['c_fly'], "9")
    
    pdf.ln(5)
    
    # --- PYTANIA KONTROLNE ---
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(2, 132, 199)
    pdf.cell(0, 10, "QUESTIONS 10 - 14 (GENERAL ANSWERS):", ln=True)
    
    questions = [
        ("10. Primary purpose of trip is business?", "NO (X)"),
        ("11. Fruits, plants, meats, food?", "NO (X)"),
        ("12. Near livestock / farms?", "NO (X)"),
        ("13. Currency over $10,000 U.S.?", "NO (X)"),
        ("14. Commercial merchandise?", "NO (X)"),
    ]
    
    for q, ans in questions:
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(120, 7, q)
        pdf.set_font("helvetica", "B", 10)
        pdf.set_text_color(198, 40, 40)
        pdf.cell(0, 7, ans, ln=True)

    pdf.ln(5)
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(2, 132, 199)
    pdf.write(7, "15. Visitors - total value of articles: ")
    pdf.set_text_color(198, 40, 40)
    pdf.write(7, f"${d['c_15']}\n")

    # --- STOPKA ---
    pdf.set_y(-25)
    pdf.set_font("helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, "Generated by Operation Iowa Hub '26 | Happy Travels!", align='C')

    # KLUCZOWA POPRAWKA: Konwersja bytearray na bytes
    return bytes(pdf.output())
