from fpdf import FPDF
import io

def generate_customs_pdf(d):
    pdf = FPDF()
    pdf.add_page()
    
    # Nagłówek
    pdf.set_fill_color(224, 242, 254) # Jasnoniebieski jak w UI
    pdf.rect(0, 0, 210, 40, 'F')
    
    pdf.set_font("helvetica", "B", 16)
    pdf.set_text_color(2, 132, 199)
    pdf.cell(0, 15, "CUSTOMS DECLARATION", ln=True, align='C')
    
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 5, "CBP Form 6059B (Traveler Cheat Sheet)", ln=True, align='C')
    pdf.ln(10)
    
    # Dane
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("helvetica", "", 10)
    
    def add_field(label, value, num):
        pdf.set_font("helvetica", "B", 10)
        pdf.set_text_color(2, 132, 199)
        pdf.write(5, f"{num}. {label}: ")
        pdf.set_font("helvetica", "B", 11)
        pdf.set_text_color(198, 40, 40)
        pdf.write(5, f"{value}\n")
        pdf.ln(4)

    add_field("Family Name, First Name", f"{d['c_last']} {d['c_first']}", "1")
    add_field("Birth date (MM/DD/YY)", d['c_dob'], "2")
    add_field("No. of family members traveling with you", str(d['c_mem']), "3")
    add_field("U.S. Street Address / Hotel", f"{d['c_street']}, {d['c_city']}, {d['c_state']}", "4")
    add_field("Passport Country / Number", f"{d['c_pass_country']} / {d['c_pass_no']}", "5-6")
    add_field("Country of Residence", d['c_residence'], "7")
    add_field("Countries visited on this trip", d['c_visited'], "8")
    add_field("Airline / Flight No.", d['c_fly'], "9")
    
    pdf.ln(5)
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(2, 132, 199)
    pdf.cell(0, 10, "QUESTIONS 10 - 15 (GENERAL ANSWERS):", ln=True)
    
    questions = [
        ("10. Business Trip?", "NO"),
        ("11. Food/Plants/Meats?", "NO"),
        ("12. Near livestock?", "NO"),
        ("13. Currency over $10k?", "NO"),
        ("14. Commercial merchandise?", "NO"),
    ]
    
    for q, ans in questions:
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(100, 7, q)
        pdf.set_font("helvetica", "B", 10)
        pdf.set_text_color(198, 40, 40)
        pdf.cell(0, 7, ans, ln=True)

    pdf.ln(5)
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(2, 132, 199)
    pdf.write(5, "15. Total value of articles: ")
    pdf.set_text_color(198, 40, 40)
    pdf.write(5, f"${d['c_15']}\n")

    # Stopka
    pdf.set_y(-30)
    pdf.set_font("helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, "Generated by Operation Iowa Hub '26", align='C')

    return pdf.output()
